# Generated by Django 3.2.16 on 2022-11-15 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_userprofile_default_full_name'),
        ('blog', '0002_alter_blog_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='commenter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commenter', to='profiles.userprofile'),
        ),
    ]
