# Generated by Django 3.2.16 on 2022-11-22 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blog_excerpt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='featured_image',
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_image',
            field=models.ImageField(default='placeholder', upload_to='', verbose_name='blog_image'),
        ),
        migrations.AddField(
            model_name='blog',
            name='logo_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
