# Generated by Django 3.2.16 on 2022-11-22 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20221122_2221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='logo_url',
            new_name='blog_image_url',
        ),
    ]
