# Generated by Django 3.2.16 on 2022-11-17 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_rename_stores_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='country',
        ),
        migrations.RemoveField(
            model_name='store',
            name='county',
        ),
        migrations.RemoveField(
            model_name='store',
            name='email',
        ),
        migrations.RemoveField(
            model_name='store',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='store',
            name='postcode',
        ),
        migrations.RemoveField(
            model_name='store',
            name='street_address1',
        ),
        migrations.RemoveField(
            model_name='store',
            name='street_address2',
        ),
        migrations.RemoveField(
            model_name='store',
            name='town_or_city',
        ),
        migrations.AddField(
            model_name='store',
            name='owner',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='StoreAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address1', models.CharField(max_length=80)),
                ('street_address2', models.CharField(blank=True, max_length=80, null=True)),
                ('town_or_city', models.CharField(max_length=40)),
                ('county', models.CharField(blank=True, max_length=80, null=True)),
                ('country', models.CharField(blank=True, max_length=80, null=True)),
                ('postcode', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_address', to='stores.store')),
            ],
        ),
    ]
