# Generated by Django 3.2.16 on 2022-11-17 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_auto_20221117_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeaddress',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store', to='stores.store'),
        ),
    ]
