# Generated by Django 3.2.16 on 2022-11-18 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_store_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeaddress',
            name='id',
        ),
        migrations.AlterField(
            model_name='store',
            name='about',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='storeaddress',
            name='store',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='stores.store'),
        ),
    ]
