# Generated by Django 3.2.16 on 2022-11-18 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0007_auto_20221118_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='about',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='storeaddress',
            name='country',
            field=models.CharField(default='', max_length=80),
            preserve_default=False,
        ),
    ]
