# Generated by Django 3.2.16 on 2022-11-18 01:55

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0008_auto_20221118_0133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('staff_photo', cloudinary.models.CloudinaryField(default='staff_placeholder', max_length=255, verbose_name='staff')),
                ('job_title', models.CharField(max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('start_date', models.DateTimeField()),
                ('staff_number', models.CharField(max_length=6)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='stores.store')),
            ],
        ),
    ]
