# Generated by Django 3.2.16 on 2022-11-18 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0009_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staff_number',
            field=models.CharField(max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='start_date',
            field=models.DateField(),
        ),
    ]
