# Generated by Django 3.2.16 on 2022-11-18 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0012_storelocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storelocation',
            name='id',
        ),
        migrations.AddField(
            model_name='storelocation',
            name='store',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='stores.store'),
            preserve_default=False,
        ),
    ]
