# Generated by Django 3.2.16 on 2022-11-18 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0013_auto_20221118_2017'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StoreLocation',
        ),
    ]
